import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { GeminiProvider } from "@/contexts/GeminiContext";
import { Toaster } from "@/components/ui/toaster";
import { ScoreProvider } from "@/contexts/ScoreContext";
import { FireIcon } from "@heroicons/react/16/solid";
import ScoreFlame from "@/components/ScoreFlame";
import Header from "@/components/Header";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <GeminiProvider>
          <ScoreProvider>
            <Header />

            {children}
          </ScoreProvider>
        </GeminiProvider>
        <Toaster />
      </body>
    </html>
  );
}
