import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Toaster } from "@/components/ui/toaster";
import { GeminiProvider } from "@/contexts/GeminiContext";
import { ScoreProvider } from "@/contexts/ScoreContext";
import { ClerkProvider } from "@clerk/nextjs";

import Header from "@/components/Header";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "TurkishHub",
  description: "Generated by TurkishHub",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={inter.className}>
          <GeminiProvider>
            <ScoreProvider>
              <Header />

              {children}
            </ScoreProvider>
          </GeminiProvider>
          <Toaster />
        </body>
      </html>
    </ClerkProvider>
  );
}
